<br/>
<nav class="navbar navbar-expand-lg  navbar-light style="background-color: #fbc7d4;"">
    <a class="navbar-brand" href="index.php">Taxonomia</a>

    <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
            <a class="nav-link" href=""> Cadastrar:
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_familia.php"> Fam&iacutelia </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_especie.php"> Esp&eacutecie </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="form_genero.php"> G&ecircnero </a>
        </li>   
        <li class="nav-item active">
            <a class="nav-link" href=""> Listar:
                <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="familia.php"> Fam&iacutelia </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="especie.php"> Esp&eacutecie </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="genero.php"> G&ecircnero </a>
        </li>       
    </ul>
</nav>
